# Generated by Django 3.1.3 on 2020-11-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='num_stars',
            field=models.IntegerField(choices=[(1, 'Worst'), (2, 'Bad'), (3, 'Not bad'), (4, 'Good'), (5, 'Excelent')]),
        ),
        migrations.AlterField(
            model_name='musician',
            name='instrument',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
